services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8180:8080"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./New Direction Docs:/app/New Direction Docs:ro
      - ./Unit Testing:/app/Unit Testing:ro
